### ISSUE TITLE
docker版的吗？请问如何使用呢？？

### ISSUE THREAD

**Issue by hyy34** [thinkways/CTList#1]

**Comment by thinkways** [comment]
你可以使用已经制作好的docker镜像 thinkinn/ctlist。
一个典型的docker-compose配置如下：
```
version: '3'
services:
  ctlist:
  image: thinkinn/ctlist:latest
  reatart: always
  volumes:
    - ./ctlist:/conf
  environment:
    - AUTH_TOKEN=1231234214324234(你的token)
```
